export const ADD_TRANSPORT = "ADD_TRANSPORT";
export const ADD_TRANSPORT_LIST = "ADD_TRANSPORT_LIST";
export const REMOVE_TRANSPORT = "REMOVE_TRANSPORT";

export const ADD_STORAGE = "ADD_STORAGE";
export const ADD_STORAGES_LIST = "ADD_STORAGES_LIST";
export const REMOVE_STORAGE = "REMOVE_STORAGE";

export const ADD_TARIFF = "ADD_TARIFF";
export const ADD_TARIFFS_LIST = "ADD_TARIFFS_LIST";
export const REMOVE_TARIFF = "REMOVE_TARIFF";

export const ADD_ROUTE_LIST = "ADD_ROUTE_LIST";
export const ADD_ROUTES_LIST = "ADD_ROUTES_LIST";
export const REMOVE_ROUTE_LIST = "REMOVE_ROUTE_LIST";