export const ADD_TRANSPORT = "ADD_TRANSPORT";
export const ADD_TRANSPORT_LIST = "ADD_TRANSPORT_LIST";
export const REMOVE_TRANSPORT = "REMOVE_TRANSPORT";
export const ADD_STORAGE = "ADD_STORAGE";
export const ADD_STORAGES_LIST = "ADD_STORAGES_LIST";
export const REMOVE_STORAGE = "REMOVE_STORAGE";
